### ISSUE TITLE
Datadog buildpack no longer participates in a Node.js build without a package manager

### ISSUE THREAD

**Issue by thitch97** [paketo-buildpacks/datadog#170]
The `node-start` order group in the language family [buildpack for Node.js](https://github.com/paketo-buildpacks/nodejs) is meant to support running Node.js applications which do not utilize a package manager such as `npm` or `yarn`. With the [recent changes](https://github.com/paketo-buildpacks/datadog/pull/164) to include `node_modules` in this buildpack's detection criteria, it is no longer possible for the buildpack to participate in such a build (these apps do not have `node_modules`).

## Expected Behavior
When `BP_DATADOG_ENABLED` is set to true and `node_modules` are not present, I can build a Node.js application which uses Datadog.

## Current Behavior
The buildpack for Datadog does not participate in a build where the above criteria have been met.

## Steps to Reproduce

1. Clone the Paketo samples repo and navigate to the `no-package-manager` [sample app](https://github.com/paketo-buildpacks/samples/tree/main/nodejs/no-package-manager) under the `nodejs` subdirectory.
2. `pack build` the application with the `BP_DATADOG_ENABLED` env var set to `true`
3. Observe that `Buildpack for Datadog` does not appear in the build logs.

**Comment by dmikusa** [comment]
This was an intentional change.

The problem is that `node` is not a sufficient criteria because a.) node-engine provides `node` and 2.) datadog requires `node` thus you always have a buildplan match when the two are used in conjunction.

We needed some additional criteria to say not only is Node.js installed, but we have an application present as well. We used the `node_modules` plan entry for that. If there is another buildplan entry we can use to support this additional use case we can add that too, but we can't add just `node` as it will trigger false positives.

Hope that makes sense. If not, please let me know and I can explain further.
