### ISSUE TITLE
Buildpack downloads from Maven central but does not consider ~/.m2/settings.xml

### ISSUE THREAD

**Issue by exde3297** [paketo-buildpacks/datadog#94]
## Expected Behavior
Buildpack downloads Datadog Java Agent from company Maven proxy server.

## Current Behavior
Buildpack tries to download Datadog Java Agent from Maven central. 

## Possible Solution
Buildpack uses Maven settings.xml or allows defining HTTP proxy variables, for instance, to ignore invalid certificates.

## Steps to Reproduce

1. Add mirror to Maven settings.xml
```
<mirror>
  <id>nexus</id>
  <mirrorOf>central</mirrorOf>
  <url>https://my-company.org/artifacts/repository/maven/</url>
</mirror>
```
2. Add Datadog env var to pom.xml:
```
<env>
  <BP_DATADOG_ENABLED>true</BP_DATADOG_ENABLED>
</env>
```
4. Execute build image using Maven:
```
mvn spring-boot:build-image
```
5. Maven build will fail with the following console output:
```
[INFO]     [creator]     Paketo Buildpack for Datadog 2.3.0
[INFO]     [creator]       https://github.com/paketo-buildpacks/datadog
[INFO]     [creator]       Datadog Java Agent 0.109.0: Contributing to layer
[INFO]     [creator]         Downloading from https://repo1.maven.org/maven2/com/datadoghq/dd-java-agent/0.109.0/dd-java-agent-0.109.0.jar
[INFO]     [creator]     unable to invoke layer creator
[INFO]     [creator]     unable to get dependency datadog-agent-java
[INFO]     [creator]     unable to download https://repo1.maven.org/maven2/com/datadoghq/dd-java-agent/0.109.0/dd-java-agent-0.109.0.jar
[INFO]     [creator]     unable to request https://repo1.maven.org/maven2/com/datadoghq/dd-java-agent/0.109.0/dd-java-agent-0.109.0.jar
[INFO]     [creator]     Get "https://repo1.maven.org/maven2/com/datadoghq/dd-java-agent/0.109.0/dd-java-agent-0.109.0.jar": x509: certificate signed by unknown authority
[INFO]     [creator]     ERROR: failed to build: exit status 1
```

## Motivations

This prevents me from using Paketo, as I need the Datadog Java Agent inside the image. I can import the certificate into my local Java installation, but this will only work for a short time, as the certificate from the proxy server is only valid for two weeks.

**Comment by dmikusa** [comment]
The buildpack doesn't install using Maven, but it does fetch resources from Maven Central. This is just coincidence and happens because that is where Datadog has chosen to distribute their agent.

The buildpack has [metadata](https://github.com/paketo-buildpacks/datadog/blob/main/buildpack.toml#L40-L52) which indicates where to fetch the Datadog agent. If you want to pull from a different location, you can use a [dependency mapping](https://paketo.io/docs/howto/configuration/#dependency-mappings) to change where it pulls from.

In addition, if you need to specify [proxy settings](https://paketo.io/docs/howto/configuration/#proxy-configuration) there is a standard way to do that too.

Lastly, if you need to have custom CA certificates trusted, like your corporate CA certs, you can [do that as well](https://paketo.io/docs/howto/configuration/#ca-certificates).

Hope that helps!
